### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by davidx**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by davidx** [comment]
### Build Status for thumbot/prtester/pulls/7:

Looks good @davidx!  :+1:

### MERGE   OK

> Started at: 2016-08-09 12:37
> Duration: 3 seconds.
> Result:  OK
> Message: Merge Success: bdde1d270a8c67a372da55ebe7b07f47e2782edf onto target branch: master
> Exit Code:  OK

```



Updating ae97ffe..bdde1d2
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

### BUILD   OK

> Started at: 2016-08-09 12:37
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0

```

cd /tmp/thumbs/thumbot_prtester_7 && make build

BUILD OK


```

---

### TEST   OK

> Started at: 2016-08-09 12:37
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0

```

cd /tmp/thumbs/thumbot_prtester_7 && make test

TEST OK


```

---

**Comment by davidx** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by davidx** [comment]
Code reviews from: _@davidpuddy1_, _@bobsmith1_.

##### Merging and closing this PR.

**Pull request closed without merging**
