### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by davidx**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by davidx** [comment]
### Build Status for thumbot/prtester/pulls/14:

Looks good @davidx!  :+1:

### MERGE   OK

> Started at: 2016-08-09 12:43
> Duration: 4 seconds.
> Result:  OK
> Message: Merge Success: 5cd4fa0966879592849e90cf76c6b0ad6efd3d33 onto target branch: master
> Exit Code:  OK

```



Updating ae97ffe..5cd4fa0
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

### BUILD   OK

> Started at: 2016-08-09 12:43
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0

```

cd /tmp/thumbs/thumbot_prtester_14 && make build

BUILD OK


```

---

### TEST   OK

> Started at: 2016-08-09 12:43
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0

```

cd /tmp/thumbs/thumbot_prtester_14 && make test

TEST OK


```

---

**Comment by davidx** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Pull request closed without merging**
